### ISSUE TITLE
Unable to activate autopilot after disconect[Bug]: 

### ISSUE THREAD

**Issue by nath4n77** [amyinorbit/x-uns-bugs#39] opened 2021-12-19 01:39 UTC
### Version

version 1.0.11

### What happened?

# What happened: when autopilot disconnect either from overspeed or from trimming manually unable to activate it again.
Also when binding joystick to softkey disconnect AP and using this command unable to activate AP again as well

# Expected behaviour AP should be able to be connected when aircraft in control

# Attach your log file her
[Log.txt](https://github.com/a
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7740203/uns1_log.txt)
myinorbit/x-uns-bugs/files/7740202/Log.txt)
e

**Comment by amyinorbit** [comment] 2021-12-19 16:35
Thanks for the report! This isn't something that the UNS plugin controls, it's something wrong in the SASL code. Closing this for now and I'll make sure the issue is reported to Jack!

**Closed by amyinorbit** 2021-12-19 16:35 UTC
Labels: bug, q4xp-integration, autopilot
