### ISSUE TITLE
[Bug]: Unable to activate VNAV

### ISSUE THREAD

**Issue by hardy70** [amyinorbit/x-uns-bugs#12] opened 2021-11-21 18:59 UTC
### Contact Details

hardy@no-parachute.one

### Version

UNS-1 - version 1.0.9

### What happened?

TOD was calculated but off course. Unable to activate VNAV
Route: ENBR/35 OLDAS2D OLDAS DCT VALDI DCT ROBUR DCT EKVG/30/ILS V 30/ROBUR 

# Expected behaviour
Activate VNAV when reaching TOD

# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7576874/uns1_log.txt)

![Unbenannt](https://user-images.githubusercontent.com/69432621/142775290-7f882afa-f0b0-49f3-8fd0-83ed56f25722.JPG)

**Comment by amyinorbit** [comment] 2021-11-21 19:01
These are two different things -- could you create a new issue for the "Unable to enable VNAV" and add more details on the steps you took, and what the plane said?

**Comment by amyinorbit** [comment] 2021-11-21 19:01
TOD off course duplicate of #1

**Comment by hardy70** [comment] 2021-11-21 19:06
I suspect they are somehow linked. Entered descent rate after reaching cruise altitude. Received FMC message that TOD will be reached at screenshot situation. Tried to activate VNAV. No reaction, no message.

**Comment by amyinorbit** [comment] 2021-11-21 19:09
I can tell you 100% that they are not. Did you have a VNAV path shown on the PFD? If yes, please send a screenshot of the PFD. Had you selected a lower altitude?

**Closed** 2022-01-03 16:27 UTC
Labels: bug, duplicate
