### ISSUE TITLE
[Crash]: SIM Crashs due to uns-1 plugin on loading

### ISSUE THREAD

**Issue by Ericple** [amyinorbit/x-uns-bugs#7] opened 2021-11-20 02:32 UTC
### Contact Details

q1439930993@163.com

### Version

1.08

### What happened?

# What happened 
The Sim just gone with nothing happened when I tried to load the aircraft, according to the log file, it was caused by uns-1

# Expected behaviour
Simply get into the Sim

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7573777/Log.txt)

**Comment by amyinorbit** [comment] 2021-11-23 11:26
Thank you so much for your help fixing this! I have found the cause and the next update will have a fix for this:

Your navigation data contains CIFP (Coded Instrument Flight Procedures) files that are not shipped by Navigraph. That would be fine, except they reference fixes that do not exist in the database, therefore the database parser cannot construct the procedures correctly.

That shouldn't cause a crash, so the new version will load correctly and just ignore those procedures. In the meantime I'd advise you check your procedures 🙂

**Closed** 2021-11-23 11:27 UTC
Labels: crash
