### ISSUE TITLE
[Bug]: Hold Entry Issues

### ISSUE THREAD

**Issue by DerKazar** [amyinorbit/x-uns-bugs#46] opened 2022-01-02 21:34 UTC
### Version

1.0.11

### What happened?

**While testing the hold function, I've noticed three things:**
- When doing a "shallow" parallel or teardrop entry with a direct to the holds waypoint, either by pressing "DTO HOLD" or going direct to the already armed hold waypoint via the "DTO" page, the UNS will fail to generate a correct path to enter the hold and start corkscrewing. "Shallow" refers to any entry within around +/- 30° of the OUTBOUND leg.
- The UNS initially doesn't draw the correct holding with your personal dimensions on the NAV display, but rather a standard one. It only draws the correct hold one it is activated, however, not when only armed.
- If the aircraft manages to do a direct teardrop or parallel entry with a "steeper" entry than +/- 30° of the OUTBOUND leg, it will miss the waypoint by around 1 - 2 nm. It will also do the turn of the teardrop or parallel entry slightly outside the hold itself, rather than dead inside.

**The video with comments.** I remade it, no more subtitles, but timestamps.
https://www.youtube.com/watch?v=kN156BmZ8Rs

_Watchable HD Version should be ready in an hour or two._

---

**Illustration of the holds I flew in the video:**
![Holds](https://user-images.githubusercontent.com/96119645/147884526-f9b18ea1-7f4e-4a20-b791-7089866973f3.png)

_**Hold 1:**_
Left
Offset -5°
Parallel recommended, teardrop possible
= Teardrop
DTO HOLD
> Failure to enter

_**Hold 2:**_
Left
Offset 5°
Teardrop recommended, parallel possible
= Teardrop
DTO HOLD
> Failure to enter

_**Hold 3:**_
Left
Offset 20°
Teardrop only
= Teardrop
DTO HOLD
> Failure to enter

_**Hold 4:**_
Left
Offset 60°
Teardrop only
= Teardrop
DTO HOLD
> Entry successful, but not precise. Refer to the third issue.

**_Hold 5:_** (Like 3 but mirrored)
Right
Offset 20°
Teardrop only
= Teardrop
DTO HOLD
> Failure to enter

**_Hold 6:_** (Like 1 but Armed only)
Left
Offset -5°
Parallel recommended, teardrop possible
= Teardrop
Armed Only
> Entry successful

**_Hold 7:_** (Like 1, but parallel entry)
Left
Offset 5°
Teardrop recommended, parallel possible
= Parallel
DTO HOLD
> Failure to enter

**_Hold 8:_**
Left
Offset 260°
Direct only
= Direct
DTO HOLD
> Entry successful

---

Beginning was always at the same waypoint with the same track of 065°.
![DBwpt](https://user-images.githubusercontent.com/96119645/147884651-a032deea-9ef0-4d42-9a39-bb766716f9f8.png)

The flight path:
![Flight Path](https://user-images.githubusercontent.com/96119645/147884504-312feef9-8bb7-44a7-994c-2b4708b69d70.png)

The logs:
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7799506/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7799535/uns1_log.txt)

**Comment by amyinorbit** [comment] 2022-01-03 14:45
Thank you so much for the extremely detailed report and help with this! It's a head scratcher for sure, the waypoint gets marked as a fly-over but clearly isn't flown like one. I won't delay the next patch for it because I want to make sure I take the time to test this properly, but it's noted and in progress :)

**Comment by zachbf** [comment] 2022-01-07 12:20
@amyinorbit - Could I add something additional to this I noticed that is related? 

When entering a holding definintion in the real FMS, you don't need to select each item you want to put in. What I mean is, when we create a HOLD DEFN, you first select LSK_L2 and type the INBD course. When you press enter, the turn direction is auomtically highlighted, so you can enter it straight away, click enter again and then your time is highlighted straight away for input. The hold will only depect on the screen in full, once the 3 items have been confirmed. Right now, it seems you have to line-select each input as opposed to how I described above.

Of course, I'm sure you are already aware, but the FMS won't generate the hold properly until within 15 seconds of the holding fix. It will sometimes show an incorrect entry prior to this point, but it can of course be overridded manually - it might also correct itself at the -15 second mark. We have a procedure to verbally state the expected type of entry prior to entering the hold, and aligning our heading bugs in the event that the FMS turns the aircraft the wrong way. It's not perfect. lol.

**Comment by amyinorbit** [comment] 2022-01-14 19:52
@DerKazar I'd like to say thanks again for the massive amount of work you did to illustrate the issue! If anything I was a bit disappointed that the solution was but one line of code. Anyway, this should be fixed in the next build (amyinorbit/uns1@98a7f76)

**Closed by amyinorbit** 2022-01-14 19:52 UTC
Labels: bug
