### ISSUE TITLE
[CTD]: Entering hold

### ISSUE THREAD

**Issue by jvp89** [amyinorbit/x-uns-bugs#14] opened 2021-11-23 11:15 UTC
### Contact Details

jvp@meo.pt

### Version

1.09

### What happened?

Entering Hold at BAM Bremmen.
I set the hold mannualy as instructed by ATC inbound 050 Right turn, arm hold and dct hold.
while I was inbound the BAM, I was updating also the app in use to have the Trans starting in BAM.
and checking again the hold I noticed that the nav page was only showing dct BAM and not the "holding" in nav page, tried again in hold def and was unable to set it again dct hold.
overhead the BAM when supposed to join the hold CTD, I was using the WebFMS. 

[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7587494/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7587495/uns1_log.txt)
[WebFMC-log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7587496/WebFMC-log.txt)

# Attach your log file here

**Comment by amyinorbit** [comment] 2021-11-23 11:21
Thanks for the report. Could you please upload your logs again, they're all truncated in weird ways (and none of them contain the actual moment of the crash)

**Comment by amyinorbit** [comment] 2021-11-23 11:23
Possible duplicate of #5

**Closed** 2022-08-25 20:05 UTC
Labels: duplicate, crash
