### ISSUE TITLE
[CTD]: Landing roll after RNAV RNP approach

### ISSUE THREAD

**Issue by samuel1550** [amyinorbit/x-uns-bugs#11] opened 2021-11-21 17:36 UTC
### Version

1.0.9

### What happened?

During the landing roll of the RNAV 02R W approach into SBRJ (arrival ASAL1A transition KEVUN), the simulator crashed to desktop due to what I suspect to be a UNS issue. So far this has occurred twice for the same approach on two separate flights, before and after a clean reinstall. I haven't tested other approaches yet.
# When did the crash occur?
During the landing roll, shortly before reaching my stopping point near the end of the runway.
# What was the FMS doing before the crash?
Not sure as I wasn't paying particular attention to it.
# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7575648/uns1_log.txt)

**Comment by amyinorbit** [comment] 2021-11-21 19:02
Duplicate of #8

**Comment by amyinorbit** [comment] 2021-12-07 17:15
Fixed in 1.0.10

**Closed by amyinorbit** 2021-12-07 17:15 UTC
Labels: duplicate, q4xp integration, crash
