### ISSUE TITLE
[Crash]: SIM Crashs due to uns-1 plugin on loading the airplane

### ISSUE THREAD

**Issue by diegog98** [amyinorbit/x-uns-bugs#15] opened 2021-11-23 21:09 UTC
### Contact Details

gutierrez8888@gmail.com

### Version

q4xp 1.09 / UNS-1 - version 1.0.9

### What happened?

# When did the crash occur?
when loading the plane the sim crash and close
--=={This application has crashed because of the plugin: UNS-1}==--

# What was the FMS doing before the crash?

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7591025/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7591026/uns1_log.txt)

**Comment by amyinorbit** [comment] 2021-11-23 21:14
Duplicate of #7 -- fixed in the next update, this is due to incorrect navigation database files. The new version won't crash, but will obviously still ignore any invalid procedure files. Out of curiosity -- do you have any CIFP files that you have either edited by hand, or downloaded from somewhere else than Navigraph?

**Closed by amyinorbit** 2021-11-23 21:14 UTC
Labels: duplicate, q4xp integration, crash

**Comment by diegog98** [comment] 2021-11-23 21:46
yes i edited some files

**Comment by amyinorbit** [comment] 2021-11-23 23:40
That would be why. You probably created or edited a procedure that references a fix that isn't in the database, which means the FMS cannot actually build a path through it. It definitely shouldn't be crashing, but these procedures will still be ignored in the new update
